sudo: required
services:
  - docker

before_install:
  - docker build -t devr77/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true der77/docker-react npm run test -- --coverage   # -- --coverage to exit npm run test automatically

